"""add query review table

Revision ID: ab520848bc04
Revises: 767cf0f573bd
Create Date: 2024-06-05 02:55:36.427422

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ab520848bc04"
down_revision = "767cf0f573bd"
branch_labels = None
depends_on = None


def upgrade():
    # Update query_execution table to modified QueryExecutionStatus enum
    op.alter_column(
        "query_execution",
        "status",
        existing_type=sa.Enum(
            "INITIALIZED",
            "DELIVERED",
            "RUNNING",
            "DONE",
            "ERROR",
            "CANCEL",
        ),
        type_=sa.Enum(
            "INITIALIZED",
            "DELIVERED",
            "RUNNING",
            "DONE",
            "ERROR",
            "CANCEL",
            "PENDING_REVIEW",
            "APPROVED",
            "REJECTED",
        ),
        existing_nullable=True,
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "query_execution_review",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("query_execution_id", sa.Integer(), nullable=False),
        sa.Column("reviewer_id", sa.Integer(), nullable=False),
        sa.Column(
            "review_status",
            sa.Enum(
                "INITIALIZED",
                "DELIVERED",
                "RUNNING",
                "DONE",
                "ERROR",
                "CANCEL",
                "PENDING_REVIEW",
                "APPROVED",
                "REJECTED",
                name="queryexecutionstatus",
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["query_execution_id"], ["query_execution.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["reviewer_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # Remove the new value from the ENUM type
    op.alter_column(
        "query_execution",
        "status",
        existing_type=sa.Enum(
            "INITIALIZED",
            "DELIVERED",
            "RUNNING",
            "DONE",
            "ERROR",
            "CANCEL",
            "PENDING_REVIEW",
            "APPROVED",
            "REJECTED",
        ),
        type_=sa.Enum(
            "INITIALIZED",
            "DELIVERED",
            "RUNNING",
            "DONE",
            "ERROR",
            "CANCEL",
        ),
        existing_nullable=True,
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("query_execution_review")
    # ### end Alembic commands ###
